# Generated by Django 5.2.4 on 2025-07-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LecturerProfile',
        ),
    ]
